[package]
name = "lod-cloud-draw"
version = "0.1.0"
authors = ["John P. McCrae <john@mccr.ae>"]
edition = "2021"

[dependencies]
clap = "2.31.1"
serde = "*"
serde_json = "*"
serde_derive = "*"
htmlescape = "*"
noisy_float = "*"
rand = "*"
liblbfgs = "0.1.0"
