[package]
name = "lod-cloud-draw"
version = "0.1.0"
authors = ["John P. McCrae <john@mccr.ae>"]
edition = "2021"

[dependencies]
clap = "2.31.1"
serde = "*"
serde_json = "*"
serde_derive = "*"
htmlescape = "*"
noisy_float = "*"
rand = "0.8"
argmin = "0.8.1"
argmin-math = "0.3.0"
ndarray = "0.15.2"
